[package]
name = "pseudo-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.6.0"
ropey = "1.6.1"
serde = "1.0.210"
serde_json = "1.0.128"
codespan-lsp = "0.11.1"
codespan-reporting = "0.11.1"
rustc-hash = "1.1.0"

# we match `codespan-lsp`
[dependencies.lsp-types]
version = "=0.88.0"

[dependencies.logic]
path = "../logic"
