[tasks.fuzz_ci]
run_task = [
    { name = "fuzz_parser_ci" },
    { name = "fuzz_unifier_ci" },
    { name = "fuzz_ty_checker_ci" },
]

[tasks.fuzz_parser_ci]
command = "cargo"
toolchain = "nightly"
args = ["fuzzcheck", "parse::fuzz::fuzz_parser", "--stop-after-duration", "300"]

[tasks.fuzz_parser]
command = "cargo"
toolchain = "nightly"
args = ["fuzzcheck", "parse::fuzz::fuzz_parser"]

[tasks.fuzz_unifier_ci]
command = "cargo"
toolchain = "nightly"
args = ["fuzzcheck", "ty::fuzz::fuzz_unifier", "--stop-after-duration", "300"]

[tasks.fuzz_unifier]
command = "cargo"
toolchain = "nightly"
args = ["fuzzcheck", "ty::fuzz::fuzz_unifier"]

[tasks.fuzz_ty_checker_ci]
command = "cargo"
toolchain = "nightly"
args = [
    "fuzzcheck",
    "ty::fuzz2::test_type_checker",
    "--stop-after-duration",
    "300",
]

[tasks.fuzz_ty_checker]
command = "cargo"
toolchain = "nightly"
args = ["fuzzcheck", "ty::fuzz2::test_type_checker"]


[tasks.tests]
command = "cargo"
toolchain = "nightly"
args = ["test"]
env = { "RUSTFLAGS" = "--cfg=disable_fuzzcheck" }
